version: '3.8'
name: url-short-infra
services:
  mysql:
    container_name: url-short-mysql
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=url_shortening_db
      - MYSQL_ROOT_PASSWORD=123456789*
    ports:
      - '3306:3306'

  redis:
    container_name: url-short-redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT=6379
    depends_on:
      - mysql

  zookeeper:
    container_name: url-short-zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - "2182:2181"
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    depends_on:
      - mysql

  kafka-0:
    container_name: url-short-kafka-0
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:29094,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - mysql
      - zookeeper
    
#  notes-app:
#    image: notes
#    depends_on:
#      - mysql
#      - redis